### ISSUE TITLE
Make database URL, VENDORED_PATH, VENDORED_TIMESTAMP, USER_PATH configurable

### ISSUE THREAD

**Issue by mingleiwang** [rubysec/bundler-audit#102]
Hey, 

we are consuming bundler-audit in our CI builds and we don't want to hit https://github.com/rubysec/ruby-advisory-db.git continuously, so we want to make database URL configurable. Also make other global parameters like  VENDORED_PATH, VENDORED_TIMESTAMP, USER_PATH which will make this gem to have broader usage.

I can make a pull request if you want.

**Comment by mingleiwang** [comment]
any updates on this? Will you accept this pull request? Do you have any concerns?

**Comment by postmodern** [comment]
This seems very invasive. Perhaps we could just add a `--no-update` option to the check subcommand?

**Comment by mingleiwang** [comment]
But we still want to keep the database up-to-date. If we can configure database URL, we can maintain our own database(our own github instance), then we don't need to hit public github.com frequently.

**Comment by mingleiwang** [comment]
any updates on this?

**Comment by postmodern** [comment]
This seems like a specific use-case (aka using a different ruby-advisory-db repo). Plus I really don't have much time for OSS work right now. You should go ahead and fork bundler-audit for your own purposes.

**Comment by kpshek** [comment]
@postmodern - It's not that we want to use a different set of data but rather a local mirror of the ruby-advisory-db repository.

Is it still the case that you don't have time for OSS work? If so, would you entertain bringing on other committers to this project?
