### ISSUE TITLE
ERROR: "bundle-audit check" was called with arguments ["--update"]

### ISSUE THREAD

**Issue by bigtunacan** [rubysec/bundler-audit#103]
When running `bundle-audit check --update` as described in the README.md it throws an error.

    ERROR: "bundle-audit check" was called with arguments ["--update"]
    Usage: "bundle-audit check"

I worked around this by using `bundle-audit update && bundle-audit check`, but thought you might want to be aware so the README can be updated if this is no longer supported or fixed if it's a bug.

**Comment by mingleiwang** [comment]
which version is your bundler-audit? The bundle-audit check with --update is not available yet in rubygem.

**Comment by chrisnicola** [comment]
And how long will that be?

**Comment by 007** [comment]
Same question here - is there an ETA for an update to rubygem @postmodern? Could also close #111.

**Comment by connorshea** [comment]
I just ran into the same issue, any updates on a release?

**Comment by postmodern** [comment]
Finally released 0.5.0.

**Comment by jekuno** [comment]
Thanks! :+1:
