### ISSUE TITLE
Is-it-vulnerable reports vulnerabilities whereas bundler-audit does not

### ISSUE THREAD

**Issue by kofronpi** [rubysec/bundler-audit#105]
Hi,

I tried out this service (https://isitvulnerable.com/) after receiving the last Ruby weekly. It reports vulnerabilities in my `Gemfile.lock` not caught by the latest version of bundler-audit:

```
jquery-rails 4.0.3
Upgrade to:
CSRF Vulnerability in jquery-rails	~> 3.1.3
>= 4.0.4
rest-client 1.6.7
Upgrade to:
Rest-Client Gem for Ruby logs password information in plaintext	>= 1.7.3
rubygem-rest-client: session fixation vulnerability via Set-Cookie headers in 30x redirection responses
```

What should I think about it ?

Thanks

**Comment by phillmv** [comment]
Hi,

Have you tried updating it first? Try running 

```bash
bundle-audit update
```

I am one of the authors of isitvulnerable.com, and there should be no difference. If there continues to be, then there may be a bug somewhere (likely in our code) and I'd love to hear more about your Gemfile.lock.

**Comment by JuanitoFatas** [comment]
@kofronpi Have you tried `bundle-audit update`? If no problem can close this issue, thanks!
