### ISSUE TITLE
InsecureSource results in exit code 1

### ISSUE THREAD

**Issue by krigar** [rubysec/bundler-audit#106]
We're about to integrate bundler-audit into our CircleCI build process and it's looking really promising except for one fact: ignoring vulnerabilities leads to none being listed by bundler-audit, but it still exits with `exit code 1`, making CircleCI think it failed.

The reason why we ignore some vulnerabilities is because we're running on a forked version of https://github.com/spree/spree and we have to monkey patch their security patches instead of upgrading the version.

Example output:
```
$ bundle exec bundle-audit check --update --ignore OSVDB-119205 OSVDB-125699 OSVDB-125701
Updating ruby-advisory-db ...
From https://github.com/rubysec/ruby-advisory-db
 * branch            master     -> FETCH_HEAD
Already up-to-date.
ruby-advisory-db: 226 advisories
Vulnerabilities found!
```

**Comment by krigar** [comment]
Figured this one out, it was due to some git repositories in our lockfile that got marked as `InsecureSource`.

I understand the need to generate a warning when using external git repositories, but should the warning result in `vulnerable` being set to `true`?

**Comment by postmodern** [comment]
If the repositories are insecure, an attacker could MITM them and inject arbitrary code. If your threat model involves MITMing, then it makes sense to mark them as vulnerable; plus it's not hard to switch to `https://` or `git@`.

**Comment by reedloden** [comment]
Why would `git@` be more secure than `http://`? Aren't they effectively both unauthenticated and unencrypted? Are you referring to git over ssh, perhaps?

**Comment by Mange** [comment]
Yes. `git@` is the syntax for GitHub as the SSH user is named `git` there.
`git://` and `http://` are insecure.

lör 29 aug 2015 00:29 Reed Loden <notifications@github.com> skrev:

**Comment by reedloden** [comment]
Oh, duh. Reading comprehension fail. My bad.

**Comment by JuanitoFatas** [comment]
@krigar Hi! Did you solve the rake task? You could use the rake task in your project from #115 or try [this commit](https://github.com/thoughtbot/hound/commit/59663c928fe8fef4971688ea8c1cf52a68c8f6a4). 

Then I think this issue can be closed? InsecureSource results in exit code 1 is correct as @postmodern mentioned in [this comment](https://github.com/rubysec/bundler-audit/issues/106#issuecomment-135891016).

Thanks!

**Comment by postmodern** [comment]
Can this be closed?

**Comment by krigar** [comment]
Hey, yeah, I'll close it now.
