### ISSUE TITLE
country_select gem  unmoved by bundler-audit warning

### ISSUE THREAD

**Issue by obromios** [rubysec/bundler-audit#108]
bundler-audit has started giving the following warning:
```Insecure Source URI found: git://github.com/stefanpenner/country_select.git```
I reported on this on their [github site](https://github.com/stefanpenner/country_select/issues/106#issuecomment-135025936) but the response was that they do not support bundler-audit.  Can you please give me some more information about what is causing this warning so I can try to convince them it is worth fixing.

**Comment by Mange** [comment]
The git protocol is unencrypted and unauthenticated so it's vulnerable to a
MitM attack. Charge to https and all is well.

ons 26 aug 2015 20:32 Chris <notifications@github.com> skrev:

**Comment by obromios** [comment]
That makes sense and should be easy to change.

**Comment by obromios** [comment]
The bundle-audit team now understand what was going on, and it seems an easy fix.  The problem was the recommendation of using the 
```gem 'country_select', github: 'stefanpenner/country_select'```
directive rather than
```gem 'country_select', git: 'https://github.com/stefanpenner/country_select'```.
However, scudo at bundle-audit and I believe that many people would still be using the``` github:``` directive with many different gems. We were wondering if you have raised this with the bundler team, so that bundler gives a warning when it is encountered or even change the definition of ```github:```?
