### ISSUE TITLE
Please release a new version to fix our issue

### ISSUE THREAD

**Issue by jasonnoble** [rubysec/bundler-audit#111]
#98 fixed an issue we were having (We also utilize gem-in-a-box)...

Could we get a 0.4.1 version released?

Thanks.

**Comment by robbkidd** [comment]
Yes, a new release please! I'd love to use `check --update` in CI (from #103).

**Comment by Bjoernsen** [comment]
:+1:

**Comment by jaredmoody** [comment]
:+1:

**Comment by ruslankhaertdinov** [comment]
:+1:

**Comment by postmodern** [comment]
Finally released 0.5.0.
