### ISSUE TITLE
add memory leaks warnings ?

### ISSUE THREAD

**Issue by grosser** [rubysec/bundler-audit#116]
@postmodern would you merge a PR that adds these a low priority advisories ?
https://github.com/ASoftCo/leaky-gems

**Comment by postmodern** [comment]
Someone needs to submit advisories for each of these gems. Then we could add them to [ruby-advisory-db](https://github.com/rubysec/ruby-advisory-db).

**Comment by grosser** [comment]
not sure if I'm doing this right ...

 - zipruby rubysec/ruby-advisory-db#207 (actual advisory)

rest is just PRs ...
 - sidekiq rubysec/ruby-advisory-db#208
 - therubyracer rubysec/ruby-advisory-db#209
 - grape rubysec/ruby-advisory-db#210
 - celluloid rubysec/ruby-advisory-db#211

**Comment by grosser** [comment]
the PR's don't belong into ruby-advisory db ... do you think they would make sense here ... would be great to have a one-stop-shop to know your Gemfile is good ... maybe as a separate source ?

**Comment by douglascamata** [comment]
Yes! It would be great to have just one thing to tell me if there is anything wrong with my gems, from memory leaks to security stuff. Maybe we can create a db of leaky gems and another gem to check both the leaky gems db and ruby-advisor-db (just to try to look a close as possible do bundler-audit + ruby-advisor-db). Oooorrr, we can include the leaky gems db inside the gems repository (something that looks a bit more like homebrew). What you think?

**Comment by grosser** [comment]
create new database then ... in order of preference:
 - add new database to bundle-audit
 - make new database an optional part of bundle-audit
 - make new gem that checks new database by running bundle-audit with some funky hacks/arguments

**Comment by douglascamata** [comment]
@grosser I like your suggestion. Let's check if bundler-audit would welcome a memory leak database.

**Comment by douglascamata** [comment]
@grosser deleted my old comment since I thought we were talking in that `leaky-gems` issue, sorry.

**Comment by postmodern** [comment]
@grosser memory leaks are a potential DoS, and can be included in ruby-advisory-db, imho. Someone just has to request CVE/OSVDB IDs for them.

**Comment by grosser** [comment]
I don't think any of them are attackable and I don't want to report something that I don't think is a vulnerability ... what do you think about the other options ?

**Comment by grosser** [comment]
therubyracer for example is most often used in asset compilation, so getting a CVE would be useless ... so some auditing mechanism would be great :)

what do you think about adding a new database or making the database-url configureable ?
