### ISSUE TITLE
Contributing Developer HOWTO request for README

### ISSUE THREAD

**Issue by eliotsykes** [rubysec/bundler-audit#120]
Just putting together a PR, unfortunately having a little trouble getting all specs to pass with unmodified `master`. I guess I'm missing some setup steps. Here's what I've got so far:

``` bash
# Fork repo on GitHub, then ...

git clone FORK_URL

cd bundler-audit/

bundle install

bundle exec rspec
```

**Comment by postmodern** [comment]
Improved in 675724fec25f6f8a1c7828ec26aab3fcb1d92a20.
