### ISSUE TITLE
Can full Advisory ID be displayed in the output?

### ISSUE THREAD

**Issue by bethesque** [rubysec/bundler-audit#125]
Was having a play around and wondering why the following command was not ignoring the given vulnerability:

``` shell
$ be bundle-audit check --ignore 126747
Name: uglifier
Version: 2.7.1
Advisory: 126747
Criticality: Unknown
URL: https://github.com/mishoo/UglifyJS2/issues/751
Title: uglifier incorrectly handles non-boolean comparisons during minification
Solution: upgrade to >= 2.7.2
```

After doing some debugging, I found that the advisory property being used to compare to the ignore list was the `id` property ("OSVDB-126747"), but the code prints the `osvdb` property ("126747") which did not include the prefix.

``` ruby
unless ignore.include?(advisory.id)
  yield UnpatchedGem.new(gem,advisory)
end
```

``` ruby
        say "Advisory: ", :red

        if advisory.cve
          say "CVE-#{advisory.cve}"
        elsif advisory.osvdb
          say advisory.osvdb
        end
```

Is there a reason for not displaying the full Advisory ID in the output?

**Comment by reedloden** [comment]
Submitted #126 to fix this.

**Comment by batizhevsky** [comment]
Same problem.
```
Name: mail
Version: 2.5.4
Advisory: 131677
Criticality: Unknown
URL: http://www.mbsd.jp/Whitepaper/smtpi.pdf
Title: Mail Gem for Ruby vulnerable to SMTP Injection via recipient email addresses
Solution: upgrade to >= 2.6.0

```

but to add to ignore list I must pass full name `OSVDB-131677`

**Comment by postmodern** [comment]
This should be fixed with the introduction of `Advisory#identifiers` in 1b28961aef0c1951c408ab3b2c0edfcc93df5bf8.
