### ISSUE TITLE
Incorporating the rake task is incorrect documentation

### ISSUE THREAD

**Issue by vraravam** [rubysec/bundler-audit#131]
I tried to follow the documentation referenced in https://github.com/rubysec/bundler-audit/pull/115 - but there is a better solution at least for rails applications:
1) Create the file `lib/tasks/bundle_audit.rake`
2) Put the following contents:
```
require 'bundler/audit/task'

Bundler::Audit::Task.new

task default: 'bundle:audit'
```

**Comment by JuanitoFatas** [comment]
I think this feature is not released yet.

**Comment by vraravam** [comment]
Yes - but the documentation is still incorrect (even in the unreleased README)

**Comment by JuanitoFatas** [comment]
> Yes - but the documentation is still incorrect (even in the unreleased README). Compare the first line in each....

Thanks! I will open a Pull Request to fix it!

**Comment by vraravam** [comment]
im abt to do it already!
