### ISSUE TITLE
Non zero exit if DB update fails

### ISSUE THREAD

**Issue by jekuno** [rubysec/bundler-audit#136]
Currently `bundle-audit update` always returns exit code zero.

Expected: If DB update fails (e.g. due to missing network connection) a non zero exit code should be returned. This is important for failing the build on a CI system.

**Comment by tbys** [comment]
+1

**Comment by nishidayuya** [comment]
:+1:

**Comment by tbys** [comment]
Apparently this was fixed in a6c4b7898cf03f1ba5246d4ac904e634857fca4b, so I guess we just have to wait for the next gem release.

**Comment by postmodern** [comment]
Finally released 0.5.0.
