### ISSUE TITLE
Release #95

### ISSUE THREAD

**Issue by rvanlieshout** [rubysec/bundler-audit#137]
Issue #95 is fixed in master, but it hasn't been released yet. Can we expect a new release with it?

**Comment by Bjoernsen** [comment]
:+1:

**Comment by Davidslv** [comment]
A release would be good as there's a fix here that was release a month after the version was bumped https://github.com/rubysec/bundler-audit/commit/4e32fca89d75f0e249671431ff38aadc02bfb28b

**Comment by postmodern** [comment]
Finally got around to releasing 0.5.0.
