### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by darrenleeweber** [rubysec/bundler-audit#150]
```sh
cat README.md | sed -e 's/bundle audit/bundle-audit/g'
```

**Comment by postmodern** [comment]
#149 added `bin/bundle-audit` which bundler will use if you specify `bundle audit`.

**Comment by pjscopeland** [comment]
Bump. MASSIVE bump. Kept trying `$ bundle audit` and kept getting `Could not find command "audit".`

**Comment by postmodern** [comment]
Temporarily switched it back. Please do not that the master README doesn't always represent the latest stable version. For stable documentation, please see [rubydoc.info](http://rubydoc.info/gems/bundler-audit/frames).

**Comment by philCryoport** [comment]
@postmodern dude please update README.md.  That's what users find first.

**Comment by postmodern** [comment]
@philCryoport chill out. The README currently reflects version 0.6.0, which was released on 2017-07-18. Still, a git repo is not a stable source of documentation.
