### ISSUE TITLE
bundle-audit check --update errors

### ISSUE THREAD

**Issue by tibbon** [rubysec/bundler-audit#155]
Running `bundle-audit check --update` as the README suggests doesn't seem to work. 

```sh
$ bundle-audit check --update
ERROR: "bundle-audit check" was called with arguments ["--update"]
Usage: "bundle-audit check"
```

**Comment by postmodern** [comment]
According to the [ChangeLog](http://www.rubydoc.info/gems/bundler-audit/file/ChangeLog.md) `bundle-audit check --update` was added in 0.5.0.
