### ISSUE TITLE
method_missing': undefined method `this' for #<Gem::Specification...> (NoMethodError)

### ISSUE THREAD

**Issue by lucascaton** [rubysec/bundler-audit#157]
Hi there, I've got this error when running `$ bundle-audit`:

```
~/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/specification.rb:2158:in `method_missing': undefined method `this' for #<Gem::Specification:0x3ffa49ced2e4 bundler-audit-0.5.0> (NoMethodError)
```

* Ruby `2.3.1`
* Rails `4.2.7`
* bundler-audit `0.5.0`

**Comment by postmodern** [comment]
Can I see the full backtrace?

**Comment by lucascaton** [comment]
@postmodern sure!

```
$ bundle-audit
~/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/specification.rb:2158:in `method_missing': undefined method `this' for #<Gem::Specification:0x3fe73e160b9c bundler-audit-0.5.0> (NoMethodError)
  from ~/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/specification.rb:1057:in `find_active_stub_by_path'
  from ~/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:64:in `require'
  from ~/.rvm/gems/ruby-2.3.1/gems/bundler-audit-0.5.0/bin/bundle-audit:8:in `<top (required)>'
  from ~/.rvm/gems/ruby-2.3.1/bin/bundle-audit:23:in `load'
  from ~/.rvm/gems/ruby-2.3.1/bin/bundle-audit:23:in `<main>'
  from ~/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
  from ~/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by postmodern** [comment]
This may be a rubygems bug. `find_active_stub_by_path` appears to find a `Gem::StubSpecification` object which supports a `#this` method, but a `Gem::Specification` object somehow shows up instead.

**Comment by postmodern** [comment]
According to rubygem's [ChangeLog](https://github.com/rubygems/rubygems/blob/0b6befedc9ef63b20d4264de081fca5a6d8ac018/History.txt#L74-L75) they fixed a bug in 2.6.3 where `Gem::Specification.stubs` contained `Gem::Specification` objects. https://github.com/rubygems/rubygems/pull/1558 also references the `find_active_stub_by_path` method. What version of rubygems are you running?

**Comment by lucascaton** [comment]
```
$ gem -v
2.5.1
```

**Comment by lucascaton** [comment]
@postmodern I've updated RubyGems to `2.6.6` and it's working now.

Thank you!
