### ISSUE TITLE
Database.update! shall fail when git not installed

### ISSUE THREAD

**Issue by tmaier** [rubysec/bundler-audit#158]
I am using the tool (thanks for providing it) within an alpine linux docker container.

I wondered why the update feature did not work. 
It failed without error.

The reason is, that `Database.update!` fails silently when git is not installed (https://github.com/rubysec/bundler-audit/blob/master/lib/bundler/audit/database.rb#L94-L104)
- `.update!` should check if `git` is available
- `.update!` should return false or an error when `git` is not available on the system

**Comment by ZimbiX** [comment]
We've just been hit by this. Luckily, GitHub notified us about the vulnerability, or we wouldn't have known!

'Skipping update' is a very misleading message for this situation. I'd always interpreted it as 'the vulnerability database is already sufficiently up-to-date'! Not that it would **never be checking for new vulnerabilities** (unless we updated the version of `bundler-audit` - I take it it's packaged with an initial database, but haven't checked).

I'm amazed this issue has been sitting here for so long. Very glad there's a PR now to resolve it; let's get that merged =)
