### ISSUE TITLE
A queiter `check --update`

### ISSUE THREAD

**Issue by jaredbeck** [rubysec/bundler-audit#164]
`bundle-audit check --update` is noisy.

```
Updating ruby-advisory-db ...
From https://github.com/rubysec/ruby-advisory-db
 * branch            master     -> FETCH_HEAD
Already up-to-date.
Updated ruby-advisory-db
ruby-advisory-db: 273 advisories
No vulnerabilities found
```

I'd like to implement a `--quiet` flag that produces less, or no, output when successful. Any interest?

**Comment by jaredbeck** [comment]
@postmodern one week ping. Is this something you'd be interested in?

**Comment by postmodern** [comment]
@jaredbeck sounds reasonable. `check` already supports a verbose option.

**Comment by jaredbeck** [comment]
Thanks, I'll give it a try, maybe this weekend.

**Comment by jaredbeck** [comment]
Closed by https://github.com/rubysec/bundler-audit/pull/168
