### ISSUE TITLE
bundle-audit fails because of insecure URIs from Github

### ISSUE THREAD

**Issue by tiagoovieira** [rubysec/bundler-audit#174]
I updated the bundle-audit and now it's not working, this is the total output

```
Insecure Source URI found: git://github.com/rails/spring
Insecure Source URI found: git://github.com/thoughtbot/shoulda-matchers.git
Vulnerabilities found!
```

**Comment by wtfiwtz** [comment]
There is a PR here to ignore whitelisted sources: https://github.com/rubysec/bundler-audit/pull/124

**Comment by wtfiwtz** [comment]
Here's a quick fix for now: https://github.com/ActivePipe/bundler-audit/tree/ignore-warnings

**Comment by gregkare** [comment]
You shouldn't ignore these, the git protocol is clear text. You should switch to https for public repos

**Comment by wtfiwtz** [comment]
I think the issue was they were private repos, and HTTPS would not work for our current SSH key setup. If `bundler-audit` were a failing CI step then no build would ever succeed. Probably something I should look at further though 👍

**Comment by postmodern** [comment]
bundler-audit will indeed flag `git://` URIs, unless the host points to an internal IP address. I recommend using `git@...` URIs with SSH key forwarding, or host your private repos on a Git server that's you access via a VPN.
