### ISSUE TITLE
Change license type

### ISSUE THREAD

**Issue by fatal10110** [rubysec/bundler-audit#187]
Hey, I know that it was already discussed here #81, but our company was asked to remove your gem 
from our source code, because of legal (license) issue.

So is it possible to change the license? 

Thanks!

**Comment by alex-mohemian** [comment]
Yes please! We can not use this gem because of that reason.

**Comment by david-a-wheeler** [comment]
It looks like this was already resolved in #81.  I can say we don't have any problem.
