### ISSUE TITLE
Should bundler-audit verify it is up-to-date?

### ISSUE THREAD

**Issue by thbar** [rubysec/bundler-audit#20]
A thought came up while applying bundler-audit (and brakeman etc) on many projects for a client.

To avoid errors when doing bulk operations especially, it would be convenient that bundler-audit verify if it is up-to-date or not.

If the user relies on `:git` in the Gemfile, mention that there's a new commit. If there's a new version on rubygems, mention that as well etc.

Just a thought - maybe that's too much? But I'm careful and almost got bitten by that today.

What do you think?

**Comment by postmodern** [comment]
The 0.8.0 branch (which will be merged/released soon) will now auto-download/auto-update the ruby-advisory-db on each run; unless `--no-update` is given.

**Comment by postmodern** [comment]
bundler-audit 0.8.0.rc1 has been released! Please test and provide any QA feedback.

    $ gem install --pre bundler-audit
