### ISSUE TITLE
Support running without HOME set

### ISSUE THREAD

**Issue by viraptor** [rubysec/bundler-audit#201]
When running in an environment without `HOME` variable set, the app explodes with:
```
/root/unwrappr/.bundle/ruby/2.4.0/gems/bundler-audit-0.6.0/lib/bundler/audit/database.rb:41:in `join': no implicit conversion of nil into String (TypeError)
    from /root/unwrappr/.bundle/ruby/2.4.0/gems/bundler-audit-0.6.0/lib/bundler/audit/database.rb:41:in `<class:Database>'
    from /root/unwrappr/.bundle/ruby/2.4.0/gems/bundler-audit-0.6.0/lib/bundler/audit/database.rb:29:in `<module:Audit>'
    from /root/unwrappr/.bundle/ruby/2.4.0/gems/bundler-audit-0.6.0/lib/bundler/audit/database.rb:24:in `<module:Bundler>'
    from /root/unwrappr/.bundle/ruby/2.4.0/gems/bundler-audit-0.6.0/lib/bundler/audit/database.rb:23:in `<top (required)>'
    from /root/unwrappr/.bundle/ruby/2.4.0/gems/bundler-audit-0.6.0/lib/bundler/audit.rb:18:in `require'
    from /root/unwrappr/.bundle/ruby/2.4.0/gems/bundler-audit-0.6.0/lib/bundler/audit.rb:18:in `<top (required)>'
```
This should be handled in a nicer way. Maybe with a warning and reverting to a tempdir (and then to `/tmp` if necessary), rather than raising an exception.

**Comment by fatkodima** [comment]
@viraptor I'm curious, in which environments `HOME` can not be set and why? If this was unset manually, then whats usecase for this?

**Comment by viraptor** [comment]
I can't remember exactly how it happened. It was some temporary low-privilege user being activated in a CI job.

**Comment by postmodern** [comment]
We could switch to using `Gem.home` which has logic to figure out the home directory if `HOME` isn't set.

**Comment by viraptor** [comment]
@postmodern It would likely be better, but does it have a fallback if there's actually no homedir, or if the process is sandboxed in a way that home is not writable? There could be also a specific flag like `--without-home`

**Comment by postmodern** [comment]
Wouldn't it be possible to just set your own `HOME` and point it somewhere writable?

**Comment by viraptor** [comment]
Sure, it can be. If consider it a workaround rather than a solution, but it would work.

Still, an explicit message that running without HOME set is not supported would be great.

**Comment by postmodern** [comment]
Ended up using `Gem.user_home` which can infer `HOME` if it's not set.
71ea5bd3e039355cf57699f593bcc95331e67f34
