### ISSUE TITLE
Support bundler-2

### ISSUE THREAD

**Issue by unikitty37** [rubysec/bundler-audit#202]
Bundler version 2 is due soon, but bundler-audit is hard-locked to version 1:

```
└─▷ bundle update rails
The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32, java. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java`.
Fetching gem metadata from https://rubygems.org/.........
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies....
Bundler could not find compatible versions for gem "bundler":
  In Gemfile:
    bundler-audit was resolved to 0.6.0, which depends on
      bundler (~> 1.2)

    rails (~> 5.2.1) was resolved to 5.2.1.1, which depends on
      bundler (>= 1.3.0)

  Current Bundler version:
    bundler (2.0.0.pre.2)
This Gemfile requires a different version of Bundler.
Perhaps you need to update Bundler by running `gem install bundler`?

Could not find gem 'bundler (~> 1.2)', which is required by gem 'bundler-audit', in any of the sources.
```

There doesn't seem to have been a commit for a year — will Bundler v2 be supported?

**Comment by bencrouse** [comment]
so, this is fixed here: https://github.com/rubysec/bundler-audit/commit/fade76150372f18e9c2755fa11604b9b8f6a2c2e

just needs a patch release! @postmodern, any ETA on that?

**Comment by bkuhlmann** [comment]
:information_source: Hitting this issue as well. As a temporary workaround, I'm using the following solution:

``` bash
git clone git@github.com:rubysec/bundler-audit.git
cd bundler-audit
bundle install
bundle exec rake install
```

This replaces the gem with the fix on `master` for all local development. Might have to apply this workaround to the CI builds if a version release doesn't happen soon, though.

**Comment by bencrouse** [comment]
yeah, I'm in a situation where this is a gemspec dependency so I can't point directly at git without editing a lot of repos... :(

any ETA @postmodern ?

**Comment by postmodern** [comment]
The dependency has already been updated via #203. 1.6.1 is currently blocked on this one Travis failure. https://travis-ci.org/rubysec/bundler-audit/jobs/475578889

**Comment by postmodern** [comment]
@eric-pigeon fixed the regexp issue! I will be traveling tomorrow and the next day, so probably expect 0.6.1 to be released Thursday.

**Comment by mensfeld** [comment]
@postmodern as a quick reminder ;) I'm waiting for that as well (same gemspec situation).

**Comment by bencrouse** [comment]
hey @postmodern, anything else we can do push this along?

**Comment by postmodern** [comment]
I've been offline due to a really bad head cold. I prepped a release, just have to double check it, and push it up.

**Comment by bencrouse** [comment]
thanks, I'd really appreciate that. I hope you feel better soon!

**Comment by Adithya-copart** [comment]
Thanks for the update!
