### ISSUE TITLE
Database hasn't been updated for 2 years

### ISSUE THREAD

**Issue by mooreds** [rubysec/bundler-audit#210]
Looks like the ruby sec database has been updated recently: https://github.com/rubysec/ruby-advisory-db but the database associated with this gem is 2 years old. 

Any chance we can get the most recent database installed?

**Comment by mooreds** [comment]
https://github.com/rubysec/bundler-audit/tree/master/data points to the old db. Not sure how to adjust it to point to the newest, or if there is some reason for not doing so (looked at issues, didn't see any that indicated a problem).

**Comment by mooreds** [comment]
Ah, you just need to run `bundle audit update` before you run `bundle audit check` to grab the latest database.

**Comment by postmodern** [comment]
bundler-audit 0.7.0 will switch to auto-downloading the DB on first run. Afterwards, users will have to update the DB via `bundle-audit update` or the `--update` options.
