### ISSUE TITLE
Fails silently when not invoked from bash

### ISSUE THREAD

**Issue by felixhammerl** [rubysec/bundler-audit#213]
I've encountered this problem in the [hawkeye security scanner project](https://github.com/hawkeyesec/scanner-cli/): I run `bundle-audit` via node's [child_process.spawn](https://nodejs.org/api/child_process.html#child_process_child_process_spawn_command_args_options), which by default does not run it in a shell. 

Everything else (even brakeman) runs fine like this and causes no problems. Even bundle-audit has caused no problems when invoked like this a few versions back. However, when running the same thing in ruby v2.3.0, suddenly it fails silently with no output.

The solution was to run it in `/bin/bash`, as it works then as expected, see this commit: https://github.com/hawkeyesec/scanner-cli/commit/4d5c39b80dff738de0ad9a140a429df207c9bc0f

My question is: Why is this necessary?

**Comment by postmodern** [comment]
I would need a backtrace to determine the error. It may be related to bundler-audit relying on `ENV['HOME']`. I have switched to using `Gem.user_home` which can infer `HOME` if it's not set. 71ea5bd3e039355cf57699f593bcc95331e67f34

**Comment by reedloden** [comment]
Closing due to lack of response.
