### ISSUE TITLE
airbrake-ruby blacklist_keywords not working

### ISSUE THREAD

**Issue by jschoolcraft** [rubysec/bundler-audit#221]
I'm not sure if this is within the scope of bundler-audit but it bit us and might help someone else, see: https://github.com/airbrake/airbrake-ruby/issues/468 versions below `4.2.4` have the potential to ignore `blacklist_keywords` and expose that data.

Thanks for all the work you do!

**Comment by kyrylo** [comment]
Thanks for reporting @jschoolcraft. My bad for not adding it to bundler-audit. I tried to submit a CVE via the website but it errors for me when I hit "submit". I'm copying the YAML of the CVE in the hope that someone could add it manually:

```
---
gem: airbrake-ruby
date: 2019-04-10
url: https://github.com/airbrake/airbrake-ruby/issues/468
title: Blacklist keys are no longer being filtered in airbrake-ruby
description: A flaw in airbrake-ruby v4.2.3 prevented user data from being filtered
  prior to sending to Airbrake. Such data could be user passwords. Therefore, an app
  could leak user passwords without knowing it.
unaffected_versions:
- "<= 4.2.2"
- ">= 4.2.4"
patched_versions:
- "<= 4.2.2"
- ">= 4.2.4"
related_links:
- https://github.com/airbrake/airbrake-ruby/pull/469
```

**Comment by kyrylo** [comment]
I submitted this YAML in the PR for the Ruby advisory database: https://github.com/rubysec/ruby-advisory-db/pull/412

**Comment by reedloden** [comment]
Closing this out, as https://github.com/rubysec/ruby-advisory-db/pull/412 is the right place :-)
