### ISSUE TITLE
Old thor version can cause errors from Ruby 2.5

### ISSUE THREAD

**Issue by norbertszivos** [rubysec/bundler-audit#239]
We are using Rails 5.2.4 and Ruby 2.5.x and your awesome gem as well. After some gem updates the `thor` gem version was updated to `0.20.3` and when I try to run a rake command like `bundle exec rake -T` got this error: `TypeError: NameErrorCheckers is not a module`

After a long investigation I realised that the `thor` gem caused this because they start to support `did_you_mean` library. The problem is that this support is old and in the mean time the `did_you_mean` library was changed from
https://github.com/ruby/did_you_mean/blob/v1.1.3/lib/did_you_mean/spell_checkers/name_error_checkers.rb (this is using Ruby 2.4)
to
https://github.com/ruby/did_you_mean/blob/v1.2.0/lib/did_you_mean/spell_checkers/name_error_checkers.rb (this is using Ruby 2.5)

The `thor` gem was updated so version `1.x` can solve the issue, but your gem does not let us to update this gem. The `thor` gem should stay on `0.20.0` because of that.

Could you update your `thor` support, please?

**Comment by joshRpowell** [comment]
see #237

**Comment by postmodern** [comment]
bundler-audit updated the thor dependency to ` >= 0.18, < 2`.
