### ISSUE TITLE
Notify if database is old?

### ISSUE THREAD

**Issue by jamgregory** [rubysec/bundler-audit#259]
_Just a suggestion, which I'm happy to do a PR for if folks think it's useful._

---

Should bundler-audit warn if the vulnerability database if over a certain age? I recently missed updating a gem when running it because my database was pretty old (< April 2019, I think!)

Not sure if this should be customisable, or if a suitably enforced age check would work? (> 30 days old?)

Thoughts appreciated (and thanks for a great tool!) :+1:

**Comment by ge-fa** [comment]
I would probably let it error out in this case, to make this more obvious to the user. I'm not sure what an audit check offers if old, probably outdated, data is in use.

**Comment by postmodern** [comment]
In the upcoming 0.8.0 release the database will be auto-downloaded/auto-updated on every run, so this problem should hopefully go away.

**Comment by postmodern** [comment]
bundler-audit 0.8.0.rc1 has been released! Please test and provide any QA feedback.

    $ gem install --pre bundler-audit
