### ISSUE TITLE
How to get severity of a vulnerability in the report with cvss of `null`?

### ISSUE THREAD

**Issue by Vafa-Andalibi** [rubysec/bundler-audit#272]
seems like cvss can be converted to severity using the following method:

```
According to the NVD, a CVSS base score of 0.0-3.9 is considered "Low" severity; a base CVSS score of 4.0-6.9 is "Medium" severity; and base score of 7.0-10.0 is "High" severity.
```

However, in most of the record cvss is set to null. How should that be converted to severity?

**Comment by postmodern** [comment]
The `cvss_v2` or `cvss_v3` field needs to be populated in [ruby-advisory-db](https://github.com/rubysec/ruby-advisory-db) via a Pull Request. Ever since dc508d2189d9ba0f50f61208ff75f32f65d7da57, bundler-audit outputs "Unknown" if there is no CVSS score.
