### ISSUE TITLE
Installing bundler-audit is not possible on Windows throught symlink.

### ISSUE THREAD

**Issue by Draqun** [rubysec/bundler-audit#275]
Hi.

I tried today install your gem, but I got a Permission denied. These is error message.

> C:\Users\draq>gem install bundler-audit
> ERROR:  While executing gem ... (Errno::EACCES)
>    Permission denied @ rb_file_s_symlink - (../gems/rubygems-update, C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/bundler-> audit-0.7.0.1/data/ruby-advisory-db/libraries/rubygems)

Is it possible to make a fix for windows, or it is a unix only gem?

Best regards.
Draqun

**Comment by postmodern** [comment]
I'm curious if the same thing happens if you run `git clone https://github.com/rubysec/ruby-advisory-db.git`?

**Comment by Dipeshtwis** [comment]
Same error to me as well. Permission Denied.
I'm excited to see the patch for windows as well.

**Comment by MoCrispy** [comment]
This error still exists. Is there a patch or workaround for Windows yet?

**Comment by postmodern** [comment]
The `libraries/rubygems` symlink has now been removed from ruby-advisory-db.
https://github.com/rubysec/ruby-advisory-db/commit/ba981f34ba00a6d49bd690da05f335cff506835f
