### ISSUE TITLE
No longer compatible with Ruby 2.0.0 after v0.6.1

### ISSUE THREAD

**Issue by ericpetroelje** [rubysec/bundler-audit#286]
I'm trying to use bundler-audit (0.7.01) on an ancient 2.0.0 ruby project right now and getting a failure due to scanner.rb trying to call the intersect? method on a Set around line 153.  The intersect? method does not appear to exist in Ruby 2.0.0.  I'm not sure what version it was added, but the README.md file should probably be updated to reflect that a newer version of Ruby is required to use bundler-audit (it currently says >= 1.9.3).

**Comment by postmodern** [comment]
bundler-audit 0.8.0 was updated to specify `>= 2.0.0` but it is true we only test back to ruby 2.4. We could bump the requirement to `>= 2.4.0`. Also, you could try running bundler-audit under a newer ruby version that's separate from the project's ruby version or `Gemfile`.

**Comment by sandstrom** [comment]
I'm doing some issue gardening 🌱🌿 🌷 and came upon this issue. Since it's quite old I just wanted to ask if this is still relevant? If it isn't, maybe we can close this issue?

By closing some old issues we reduce the list of open issues to a more manageable set.

**Comment by postmodern** [comment]
Probably not. Ruby has a rolling release model so there's only so much we can do to continue to support older versions. Eventually users must upgrade.
