### ISSUE TITLE
Passing parameters to bundler-audit isn't working

### ISSUE THREAD

**Issue by itay-grudev** [rubysec/bundler-audit#288]
When passing any parameters to `bundler-audit` I get an error of the type:

```
ERROR: "bundle-audit check" was called with arguments ["--gemfile", "Gemfile.lock"]
Usage: "bundle-audit check"
Deprecation warning: Thor exit with status 0 on errors. To keep this behavior, you must define `exit_on_failure?` in `Bundler::Audit::CLI`
You can silence deprecations warning by setting the environment variable THOR_SILENCE_DEPRECATION.
```
Bundler audit version: `bundle-audit 0.7.0.1 (advisories: 479)`
Ruby version: `ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-linux-gnu]`

**Comment by postmodern** [comment]
You want the `--gemfile-lock` option, which was added in 0.8.0.rc1. Run `gem install --pre bundler-audit`.
