### ISSUE TITLE
Add support for Thor 1.1.0.

### ISSUE THREAD

**Issue by MrJoy** [rubysec/bundler-audit#294]
Pinning to `~> 1.0` prevents using the 1.1.0 release that came out in January -- which adds support for Ruby 3.0.  Is there a breaking change in 1.1.0 that presents a problem?

**Comment by postmodern** [comment]
The `~> X.Y` version constraint is an alias for `>= X.Y.0, < X+1.0.0` https://thoughtbot.com/blog/rubys-pessimistic-operator

```
$ cd bundler-audit/
$ bundle info thor
  * thor (1.1.0)
```

Also Ruby 3 is already included in the CI.

**Comment by MrJoy** [comment]
Ah, my mistake.  I was having trouble updating the gem and thought it was `thor` creating the conflict, but it turned out to be `ruby_audit`.  Sorry!
