### ISSUE TITLE
Error "Unknown format" with version 0.8.0

### ISSUE THREAD

**Issue by oliverklee** [rubysec/bundler-audit#297]
This happens with our project https://github.com/braingourmets/crud/ with Ruby 3.0.1.

With bundler-audit 0.8.0, I get the following error message (note: we're running everything in a container using dip):

```
Download ruby-advisory-db ...
Cloning into '/root/.local/share/ruby-advisory-db'...
remote: Enumerating objects: 5081, done.
remote: Counting objects: 100% (84/84), done.
remote: Compressing objects: 100% (60/60), done.
remote: Total 5081 (delta 32), reused 55 (delta 18), pack-reused 4997
Receiving objects: 100% (5081/5081), 929.73 KiB | 5.81 MiB/s, done.
Resolving deltas: 100% (2490/2490), done.
ruby-advisory-db:
  advisories:   488 advisories
  last updated: 2021-04-14 10:57:17 -0400
Unknown format:
```
(You can also see the complete build here: https://github.com/braingourmets/crud/pull/162/checks?check_run_id=2418852764)

With version 0.7.0.1, the problem does not occur, and the output looks like this:

```
Updating ruby-advisory-db ...
Cloning into '/root/.local/share/ruby-advisory-db'...
remote: Enumerating objects: 5081, done.
remote: Counting objects: 100% (84/84), done.
remote: Compressing objects: 100% (60/60), done.
remote: Total 5081 (delta 32), reused 55 (delta 18), pack-reused 4997
Receiving objects: 100% (5081/5081), 929.73 KiB | 3.79 MiB/s, done.
Resolving deltas: 100% (2490/2490), done.
Updated ruby-advisory-db
ruby-advisory-db: 488 advisories
No vulnerabilities found
```

**Comment by postmodern** [comment]
How did you invoke `bundle-audit`?

**Comment by oliverklee** [comment]
We're running it in a [Rake task](https://github.com/braingourmets/crud/blob/main/lib/tasks/bundler_audit.rake) and call the Bundler Audit task from that:

```ruby
desc 'Run bundler-audit'
task bundler_audit: :environment do
  Rake::Task['bundler_audit:run'].invoke
end
```

**Comment by postmodern** [comment]
While I cannot reproduce this with a simple Gemfile, Rakefile, and bundler-audit-0.8.0, what appears to be happening is that even though the `format` option has a `default` value of `"test"`, it's being set to `nil` or possibly `""` (https://github.com/rubysec/bundler-audit/blob/a6f7e4644c997ef14f47ecb1be0000647d684f8e/lib/bundler/audit/cli.rb#L39-L53). That would explain the `Unknown format:` error message. I wonder if this is another Thor bug?

### Gemfile

```ruby
source 'https://rubygems.org/'

group :development do
  gem 'rake'
  gem 'bundler-audit', '~> 0.8'
end
```

### Rakefile

```ruby
require 'rake'

require 'bundler/audit/task'
Bundler::Audit::Task.new

task default: 'bundle:audit'
```

```
$ chruby ruby-3.0
$ bundle install
$ bundle exec rake
No vulnerabilities found
```

**Comment by postmodern** [comment]
It also appears that you got the Static Analysis job passing again? https://github.com/braingourmets/crud/actions

**Comment by oliverklee** [comment]
> It also appears that you got the Static Analysis job passing again?

Ah, yes, because we pinned bundler-audit to `~>0.7.0.1`: https://github.com/braingourmets/crud/commit/9e8ae1eead7528ffbe9ca0dc0610d94f64eefcd8 :-)

**Comment by postmodern** [comment]
OK, I see your problem. In your [bundler-audit rake task](https://github.com/braingourmets/crud/blob/9e8ae1eead7528ffbe9ca0dc0610d94f64eefcd8/lib/tasks/bundler_audit.rake#L13) you are explicitly initializing the `Bundler::Audit::CLI` class (which is a Thor app) and calling the method. Thor is kind of weird and not very well designed, so calling `.new` will not initialize method options which have default values. I'd recommend instead calling `Bundler::Audit::CLI.start(["subcommand", "arg1", "arg2", ...])`.

```ruby
require 'thor'

class Test < Thor

  # option :opt, desc: 'an option'
  # option :flag, type: :boolean,
  #               desc: 'a boolean flag'

  desc 'test', 'test task'
  method_option :format, default: 'foo'
  # method_option :opt, desc: 'an option'
  # method_option :flag, type: :boolean,
  #                      desc: 'a boolean flag'
  def test
    p options[:format]
  end

end

>> Test.new.test
# nil
>> Test.start(["test"])
"foo"
```

The reason why your rake task worked with bundler-audit 0.7.x, was because [none of the method_options had default values](https://github.com/rubysec/bundler-audit/blob/v0.7.0.1/lib/bundler/audit/cli.rb#L32) yet; this changed in 0.8.0.

Also, I like that you added an `bundler_audit:update` rake tasks. Could you maybe submit a PR back to bundler-audit to add it to it's [official rake task](https://github.com/rubysec/bundler-audit/blob/a6f7e4644c997ef14f47ecb1be0000647d684f8e/lib/bundler/audit/task.rb#L19-L25)?

**Comment by oliverklee** [comment]
> Also, I like that you added an `bundler_audit:update` rake tasks. Could you maybe submit a PR back to bundler-audit to add it to it's official rake task?

Done: #298 

(I'm not sure about whether this is the right way to do this, though. I'll be grateful for feedback.)

**Comment by oliverklee** [comment]
@postmodern Thanks for looking into this! We have now updated our Rake tasks accordingly and could successfully update to version 0.8.0. :heart:
