### ISSUE TITLE
Ignoring insecure dependecy without an Advisory

### ISSUE THREAD

**Issue by gadimbaylisahil** [rubysec/bundler-audit#316]
Ignore this ticket. Solved by ignoring GHSA

**Comment by gadimbaylisahil** [comment]
What is your thoughts on adding a feature to ignore the `dependency` itself, so that it ignores all associated vulnerabilities with the given gem?

**Comment by postmodern** [comment]
That looks like output from an older version of bundler-audit. Try upgrading to 0.8.0, which should print the CVE and/or GHSA ID instead of a blank `Advisory: `.

**Comment by gadimbaylisahil** [comment]
> That looks like output from an older version of bundler-audit. Try upgrading to 0.8.0, which should print the CVE and/or GHSA ID instead of a blank `Advisory: `.

Thanks!
