### ISSUE TITLE
bundler-audit open source License issue 

### ISSUE THREAD

**Issue by nareshcool97** [rubysec/bundler-audit#393]
## Description
https://spdx.org/licenses/GPL-3.0-or-later.html
bundler-audit open source License issue on vulnerability tools.
bundler-audit GPL-3.0 license
License
[snyk:lic:rubygems:bundler-audit:GPL-3.0](https://app.snyk.io/vuln/snyk:lic:rubygems:bundler-audit:GPL-3.0)

**Comment by postmodern** [comment]
Could you clarify what the issue is? Recently the gemspec license was corrected to use a valid SPDX license of `GPL-3.0-or-later` instead of the older `GPL-3.0+` syntax.
ae4e6eeff71a168d589e1f76a974774f53098220

Do you want me to release a new version with the corrected gem license?

**Comment by nareshcool97** [comment]
yes, new version with corrected gem license would help. Thanks

**Comment by postmodern** [comment]
Fixed in 0.9.2. https://rubygems.org/gems/bundler-audit
