### ISSUE TITLE
No longer vendor ruby-advisory-db, but instead auto-download it

### ISSUE THREAD

**Issue by postmodern** [rubysec/bundler-audit#61]
Since ruby-advisory-db is being updated so frequently, it doesn't make sense to use bundler-audit with a vendored version. Instead, bundler-audit could automatically clone/update the ruby-advisory-db ensuring it was always up-to-date. This would simplify the `Database.path` logic, at the cost of requiring a network connection.

**Comment by noahgibbs** [comment]
Good. When I just installed the gem and ran it, it told me "no vulnerabilities" (very wrong!)

I figured out that I needed to update, but... That could have been dangerous :-)

Thanks!

**Comment by ZeroChaos-** [comment]
for the purposes of testing at install time it may be nice to keep a db in the install and allow it to be updated.  the real kicker would be to warn people when a sync/update hasn't been performed for X days.

**Comment by postmodern** [comment]
Finally removed the vendored database in the 0.7.0 branch and fixed the specs. Only the CLI specs are failing. The vendored database has caused lots of issues where users complained the database was too old, not realizing they could update via `bundler-audit update`.

**Comment by postmodern** [comment]
Closing this now that bundler-audit 0.8.0.rc1 and 0.8.0.rc2 have been released. 0.8.0 will be released soon.
