### ISSUE TITLE
Don't say 'Unpatched versions found!' when it's only an insecure source

### ISSUE THREAD

**Issue by mccabe615** [rubysec/bundler-audit#67]
When running bundler-audit with no vulnerable gems, it still outputs 'Unpatched versions found!' if an insecure source is found.

$: bundle-audit
Insecure Source URI found: http://rubygems.org/
Unpatched versions found!

**Comment by aprescott** [comment]
This has been fixed by #84, which was merged. I believe this issue can be closed.

**Comment by mccabe615** [comment]
:+1:

**Comment by obromios** [comment]
I just installed bundler-audit, then did ```gem update bundler-audit```, then did ```bundle-audit update```, then ran it, and it successfully found the latest rails security problems, so it is a great gem. However, when I fixed the problems, and ran bundle-audit again, I had the following output:
```
Insecure Source URI found: http://rubygems.org/
Unpatched versions found!
```
