### ISSUE TITLE
Whitelist insecure git sources if they are internal IPs

### ISSUE THREAD

**Issue by postmodern** [rubysec/bundler-audit#72]
Resolve the host of insecure git sources and check if they are non-routable IPs.

**Comment by igorescobar** [comment]
:+1:

**Comment by sds** [comment]
I've added a pull request for this feature.

In addition to automatically ignoring internal IPs, how would you feel about adding an option allowing you to ignore certain hosts? I'd be happy to submit a pull request if that aligns with the goals of this project.

**Comment by postmodern** [comment]
Released in 0.4.0.
