### ISSUE TITLE
Issues with dynamic Gemfiles

### ISSUE THREAD

**Issue by peter-mtso** [rubysec/bundler-audit#73]
The `bundle-audit` binary is run with `ruby_executable_hooks`. By default, this wrapper uses the `noexec` functionality, documented at https://github.com/mpapis/rubygems-bundler. In turn, this executes the `Gemfile` in the current directory.

This is problematic if the `Gemfile` has early termination code, such as

``` ruby
if !File.exists?("/usr/bin/foo")
 Bundler.ui.error("You must install `foo` first!")
 raise SystemExit.new(1)
end
```

When executing under `bundle-audit`, the error isn't shown, and the command fails silently. This is undesirable, and may lead users to believe that their project passed the audit.

I'm unsure if we can opt out of this somewhere in the gemspec, though that would probably be best. At the least, we should document it and suggest exporting `NOEXEC_EXCLUDE=bundle-audit` from one's shell to disable `Gemfile` parsing.

Thanks!

**Comment by JuanitoFatas** [comment]
@peter-mtso Is this still an issue for you? If not, could you close this issue please? Thank you.
