### ISSUE TITLE
Ignore internal gem source

### ISSUE THREAD

**Issue by igorescobar** [rubysec/bundler-audit#88]
In our company we got an internal gem server and we need do ignore the warning:
```Insecure Source URI found: http://gems.test.com.br/```

Help?

**Comment by mikeatlas** [comment]
Seems like you could fork and make a PR, not too difficult

https://github.com/rubysec/bundler-audit/blob/d2cad988ade5158cdc75b4153867df36f86e269a/lib/bundler/audit/scanner.rb#L68-L82

**Comment by postmodern** [comment]
See #72.

**Comment by postmodern** [comment]
Released in 0.4.0.

**Comment by igorescobar** [comment]
Thank you guys! Awesome! :+1:
