### ISSUE TITLE
Release under MIT

### ISSUE THREAD

**Issue by grosser** [rubysec/bundler-audit#9]
Lot's of people are scared of GPL, relasing under MIT would be great/simpler/no need to explain to legal department etc

**Comment by postmodern** [comment]
@antoncohen pointed out that now bundler-audit provides a rake task which can be loaded into a Rakefile, does that constitute linking? If the Rakefile is only used during development, does that mean the whole project becomes a derivative work?

**Comment by minifast-julia** [comment]
Another vote in favor of an MIT release, in support of secure velocity.

**Comment by postmodern** [comment]
Going to eventually extract a ruby-advisory-db library and release that as MIT. bundler-audit is just a CLI tool, not intended to be used as a library.
