### ISSUE TITLE
Still seeing 'Unpatched versions found' message

### ISSUE THREAD

**Issue by obromios** [rubysec/bundler-audit#93]
I just installed bundler-audit, then did gem update bundler-audit, then did bundle-audit update, then ran it, and it successfully found the latest rails security problems, so it is a great gem. However, when I fixed the problems, and ran bundle-audit again, I had the following output:

Insecure Source URI found: http://rubygems.org/
Unpatched versions found!

However, according to issue #67 this should no longer happen.

**Comment by mccabe615** [comment]
It looks like you have a Rubygems source that's using HTTP instead of HTTPS. Check the top of your Gemfile and make sure all sources are using https URLs and then rerun bundler audit. If that doesn't work can you share your Gemfile.lock?

**Comment by postmodern** [comment]
I'm also working on releasing 0.4.0, which changes the text to "Vulnerabilities found!".

**Comment by obromios** [comment]
Thank you for your help, I changed the source to 
```
source 'https://rubygems.org'
```
and it eliminated the warning message. 

As someone not from security background, I think 'Vulnerabilities found' is much clearer.  You might also consider changing your all clear message from 'No unpatched versions found' to something like 'No vulnerabilities found'.  It is unclear to me what 'unpatched versions' are and in any case 'no unpatched' is a double negative which most people find harder to process i.e. 'no unpatched'-->'patched'-->'only patched'

Anyway, thanks for this and for an important gem which should be very widely used.

Chris

**Comment by postmodern** [comment]
This should be fixed in 0.4.0.
